controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - robot_arm_waist_joint
      - robot_arm_shoulder_joint
      - robot_arm_elbow_joint
      - robot_arm_forearm_roll_joint
      - robot_arm_wrist_angle_joint
      - robot_arm_wrist_rotate_joint
  - name: fake_arm_gripper_controller
    type: $(arg execution_type)
    joints:
      - robot_arm_left_finger_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: sleep